services:
  - type: web
    name: scanner-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        generateValue: true
